---
name: second_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_app_badge: ^2.0.2
  flutter_app_badger: ^1.5.0
  flutter_compass: ^0.7.0
  flutter_riverpod: ^2.3.7
  geolocator: ^10.1.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.5.0
  google_mobile_ads: ^3.1.0
  local_auth: ^2.1.7
  permission_handler: ^10.4.3
  quick_actions: ^1.0.6
  sensors_plus: ^3.0.3
  share_plus: ^7.1.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
